
export const CATEGORIES = [
  { id:'all',        label:'All Tools',        color:'#14B8A6', bg:'rgba(20,184,166,0.12)'  },
  { id:'organize',   label:'Organise',          color:'#3B82F6', bg:'rgba(59,130,246,0.12)'  },
  { id:'edit',       label:'Edit & Annotate',   color:'#8B5CF6', bg:'rgba(139,92,246,0.12)'  },
  { id:'optimize',   label:'Optimise & Repair', color:'#22C55E', bg:'rgba(34,197,94,0.12)'   },
  { id:'secure',     label:'Security',          color:'#F59E0B', bg:'rgba(245,158,11,0.12)'  },
  { id:'convert-to', label:'Convert to PDF',    color:'#D85A30', bg:'rgba(216,90,48,0.12)'   },
  { id:'convert-from',label:'Convert from PDF', color:'#EC4899', bg:'rgba(236,72,153,0.12)'  },
  { id:'ai',         label:'AI-powered',        color:'#06B6D4', bg:'rgba(6,182,212,0.12)'   },
];

export const TOOLS = [
  // ── ORGANISE ──────────────────────────────────────────────────────────────
  { slug:'merge-pdf',        name:'Merge PDF',          desc:'Combine multiple PDF files into a single document. Reorder before merging.',        category:'organize',     icon:'GitMerge',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'split-pdf',        name:'Split PDF',           desc:'Divide a PDF into separate files by page ranges, every N pages, or single pages.', category:'organize',     icon:'Scissors',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'extract-pages',    name:'Extract Pages',       desc:'Pull out specific pages into a standalone PDF document.',                           category:'organize',     icon:'FolderInput',    accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'organize-pdf',     name:'Organise Pages',      desc:'Reorder, delete, or rearrange pages by entering a new page sequence.',             category:'organize',     icon:'LayoutGrid',     accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'delete-pages',     name:'Delete Pages',        desc:'Remove specific pages from a PDF without affecting the rest of the document.',      category:'organize',     icon:'Trash2',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'rotate-pdf',       name:'Rotate Pages',        desc:'Rotate all or selected pages by 90, 180, or 270 degrees.',                         category:'organize',     icon:'RotateCw',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'reverse-pages',    name:'Reverse Pages',       desc:'Flip the entire page sequence of a PDF to reverse order.',                         category:'organize',     icon:'ArrowLeftRight', accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'add-blank-page',   name:'Add Blank Page',      desc:'Insert empty pages at any position in your document.',                             category:'organize',     icon:'FilePlus',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'alternate-merge',  name:'Alternate Merge',     desc:'Interleave pages from two PDFs — ideal for double-sided scanner output.',          category:'organize',     icon:'Shuffle',        accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'n-up-pdf',         name:'N-Up PDF',            desc:'Print multiple pages on a single sheet — 2-up, 4-up, or 9-up layout.',            category:'organize',     icon:'LayoutGrid',     accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'pdf-to-zip',       name:'PDF to ZIP',          desc:'Archive multiple PDF files into a single compressed ZIP package.',                 category:'organize',     icon:'Archive',        accepts:['.pdf'],                       output:'zip',  working:true,  multi:true },
  { slug:'pdf-reader',       name:'PDF Reader',          desc:'View any PDF directly in your browser with a clean, distraction-free interface.',  category:'organize',     icon:'BookOpen',       accepts:['.pdf'],                       output:null,   working:true  },
  { slug:'view-metadata',    name:'View Metadata',       desc:'Inspect all embedded PDF properties: author, title, dates, and more.',             category:'organize',     icon:'Info',           accepts:['.pdf'],                       output:null,   working:true  },
  { slug:'compare-pdfs',     name:'Compare PDFs',        desc:'Highlight visual differences between two versions of a PDF document.',            category:'organize',     icon:'GitCompareArrows',accepts:['.pdf'],                     output:null,   working:true  },
  // ── EDIT & ANNOTATE ───────────────────────────────────────────────────────
  { slug:'add-watermark',    name:'Add Watermark',       desc:'Stamp a custom text or diagonal watermark across every page.',                    category:'edit',         icon:'Droplets',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'page-numbers',     name:'Page Numbers',        desc:'Add customisable page numbers to any position on every page.',                    category:'edit',         icon:'Hash',           accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'header-footer',    name:'Header & Footer',     desc:'Insert consistent header and footer text across all pages.',                      category:'edit',         icon:'LayoutTemplate', accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'background-color', name:'Background Colour',   desc:'Change the background colour of all pages in a PDF.',                            category:'edit',         icon:'PaintBucket',    accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'add-stamps',       name:'Add Stamps',          desc:'Apply text stamps such as APPROVED, DRAFT, or CONFIDENTIAL to pages.',           category:'edit',         icon:'Stamp',          accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'sign-pdf',         name:'Sign PDF',            desc:'Draw or type a signature and place it precisely on any page.',                   category:'edit',         icon:'PenLine',        accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'redact-pdf',       name:'Redact Content',      desc:'Permanently black out sensitive text or image areas from a PDF.',               category:'edit',         icon:'EyeOff',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'crop-pdf',         name:'Crop PDF',            desc:'Trim page margins by adjusting crop, media, and trim box values.',               category:'edit',         icon:'Crop',           accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'remove-annotations',name:'Remove Annotations', desc:'Delete all comments, highlights, and markup from a PDF.',                        category:'edit',         icon:'Eraser',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'remove-blank-pages',name:'Remove Blank Pages', desc:'Automatically detect and delete empty or near-empty pages.',                     category:'edit',         icon:'FileX',          accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'edit-metadata',    name:'Edit Metadata',       desc:'Update title, author, subject, keywords, and creation date.',                   category:'edit',         icon:'Pencil',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  // ── OPTIMISE ──────────────────────────────────────────────────────────────
  { slug:'compress-pdf',     name:'Compress PDF',        desc:'Reduce file size by optimising streams and removing redundant objects.',         category:'optimize',     icon:'Minimize2',      accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'repair-pdf',       name:'Repair PDF',          desc:'Attempt to recover and rebuild corrupted or damaged PDF files.',                 category:'optimize',     icon:'Wrench',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'fix-page-size',    name:'Fix Page Size',       desc:'Standardise all pages to A4, US Letter, A3, or Legal dimensions.',              category:'optimize',     icon:'RulerSquare',    accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'page-dimensions',  name:'Page Dimensions',     desc:'Analyse and display the exact dimensions of every page in the document.',       category:'optimize',     icon:'Maximize2',      accepts:['.pdf'],                       output:null,   working:true  },
  { slug:'flatten-pdf',      name:'Flatten PDF',         desc:'Merge interactive form fields and annotations into static page content.',        category:'optimize',     icon:'Layers',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'remove-metadata',  name:'Remove Metadata',     desc:'Strip all embedded metadata including author, dates, and custom properties.',   category:'optimize',     icon:'FileMinus',      accepts:['.pdf'],                       output:'pdf',  working:true  },
  // ── SECURITY ──────────────────────────────────────────────────────────────
  { slug:'protect-pdf',      name:'Protect PDF',         desc:'Set a password and restrict printing, copying, and editing permissions.',       category:'secure',       icon:'Lock',           accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'unlock-pdf',       name:'Unlock PDF',          desc:'Remove password protection from a PDF you own and have access to.',             category:'secure',       icon:'LockOpen',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'sanitize-pdf',     name:'Sanitize PDF',        desc:'Remove hidden scripts, embedded objects, and non-visible metadata.',            category:'secure',       icon:'Shield',         accepts:['.pdf'],                       output:'pdf',  working:true  },
  { slug:'convert-pdfa',     name:'Convert to PDF/A',    desc:'Convert to archival-compliant PDF/A format for long-term preservation.',        category:'secure',       icon:'ArchiveRestore', accepts:['.pdf'],                       output:'pdf',  working:true  },
  // ── CONVERT TO PDF ────────────────────────────────────────────────────────
  { slug:'image-to-pdf',     name:'Image to PDF',        desc:'Combine JPG, PNG, WEBP, or BMP images into a PDF document.',                   category:'convert-to',   icon:'Images',         accepts:['.jpg','.jpeg','.png','.webp','.bmp','.gif','.tiff'],output:'pdf',working:true,multi:true},
  { slug:'word-to-pdf',      name:'Word to PDF',         desc:'Convert DOCX documents to PDF with layout and formatting preserved.',          category:'convert-to',   icon:'FileText',       accepts:['.docx'],                      output:'pdf',  working:true  },
  { slug:'txt-to-pdf',       name:'Text to PDF',         desc:'Convert plain text files into a clean, formatted PDF document.',               category:'convert-to',   icon:'AlignLeft',      accepts:['.txt'],                       output:'pdf',  working:true  },
  { slug:'markdown-to-pdf',  name:'Markdown to PDF',     desc:'Render Markdown files into a beautifully formatted PDF.',                      category:'convert-to',   icon:'Code2',          accepts:['.md','.markdown'],            output:'pdf',  working:true  },
  { slug:'html-to-pdf',      name:'HTML to PDF',         desc:'Convert HTML files to PDF using browser rendering for pixel-perfect output.',  category:'convert-to',   icon:'Globe',          accepts:['.html','.htm'],               output:'pdf',  working:true  },
  { slug:'excel-to-pdf',     name:'Excel to PDF',        desc:'Convert XLSX spreadsheets with charts, tables, and all sheet data.',          category:'convert-to',   icon:'Table2',         accepts:['.xlsx','.xls'],               output:'pdf',  working:false, wasm:true },
  { slug:'pptx-to-pdf',      name:'PowerPoint to PDF',   desc:'Convert PPTX presentations with slides, images, and transitions.',            category:'convert-to',   icon:'Monitor',        accepts:['.pptx','.ppt'],               output:'pdf',  working:false, wasm:true },
  // ── CONVERT FROM PDF ──────────────────────────────────────────────────────
  { slug:'pdf-to-jpg',       name:'PDF to JPG',          desc:'Render every PDF page as a high-resolution JPEG image file.',                 category:'convert-from', icon:'Image',          accepts:['.pdf'],                       output:'jpg',  working:true  },
  { slug:'pdf-to-png',       name:'PDF to PNG',          desc:'Convert each PDF page to a lossless, transparent-support PNG file.',          category:'convert-from', icon:'FileImage',      accepts:['.pdf'],                       output:'png',  working:true  },
  { slug:'pdf-to-text',      name:'PDF to Text',         desc:'Extract all text content from a PDF as a plain text file.',                   category:'convert-from', icon:'FileType',       accepts:['.pdf'],                       output:'txt',  working:true  },
  { slug:'pdf-to-word',      name:'PDF to Word',         desc:'Convert PDF to editable DOCX format with text extraction and layout hints.', category:'convert-from', icon:'FileOutput',     accepts:['.pdf'],                       output:'txt',  working:true  },
  { slug:'pdf-to-html',      name:'PDF to HTML',         desc:'Extract PDF content and structure into an HTML document.',                    category:'convert-from', icon:'Code',           accepts:['.pdf'],                       output:'html', working:true  },
  { slug:'pdf-to-csv',       name:'PDF to CSV',          desc:'Extract tabular data from PDF pages into a comma-separated spreadsheet.',     category:'convert-from', icon:'TableProperties',accepts:['.pdf'],                      output:'csv',  working:true  },
  // ── OCR ───────────────────────────────────────────────────────────────────
  { slug:'ocr-pdf',          name:'OCR — Make Searchable',desc:'Add a searchable text layer to scanned PDFs using machine learning.',        category:'optimize',     icon:'ScanText',       accepts:['.pdf'],                       output:'pdf',  working:true  },
  // ── AI ────────────────────────────────────────────────────────────────────
  { slug:'summarize-pdf',    name:'Summarise PDF',       desc:'Generate a concise, structured AI summary of any PDF document.',             category:'ai',           icon:'Sparkles',       accepts:['.pdf'],                       output:null,   working:true, ai:true },
  { slug:'translate-pdf',    name:'Translate PDF',       desc:'Translate a PDF into any language while preserving the original layout.',    category:'ai',           icon:'Languages',      accepts:['.pdf'],                       output:'pdf',  working:true, ai:true },
  { slug:'chat-pdf',         name:'Chat with PDF',       desc:'Ask questions and get cited answers directly from your document.',           category:'ai',           icon:'MessageCircle',  accepts:['.pdf'],                       output:null,   working:true, ai:true },
];

export function getBySlug(slug) { return TOOLS.find(t=>t.slug===slug)||null; }
export function getCatMeta(id)  { return CATEGORIES.find(c=>c.id===id)||CATEGORIES[0]; }
