export const TOOL_CATEGORIES = [
  { id: 'organize', label: 'Organise & Manage', color: '#D85A30' },
  { id: 'edit', label: 'Edit & Annotate', color: '#378ADD' },
  { id: 'optimize', label: 'Optimise & Repair', color: '#5DCAA5' },
  { id: 'secure', label: 'Security', color: '#EF9F27' },
  { id: 'convert-to', label: 'Convert to PDF', color: '#AFA9EC' },
  { id: 'convert-from', label: 'Convert from PDF', color: '#ED93B1' },
  { id: 'ai', label: 'AI-powered', color: '#5DCAA5' },
];

export const ALL_TOOLS = [
  // ── ORGANISE & MANAGE ──────────────────────────────────────────────────────
  { id:'merge-pdf', slug:'merge-pdf', name:'Merge PDF', desc:'Combine multiple PDFs into one document. Drag to reorder before merging.', category:'organize', badge:null, icon:'combine', color:'rgba(216,90,48,0.2)', iconColor:'#F0997B', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'split-pdf', slug:'split-pdf', name:'Split PDF', desc:'Extract pages or ranges into separate PDF files.', category:'organize', badge:null, icon:'scissors', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'extract-pages', slug:'extract-pages', name:'Extract Pages', desc:'Pull specific pages out as a standalone document.', category:'organize', badge:null, icon:'ungroup', color:'rgba(93,202,165,0.2)', iconColor:'#5DCAA5', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'organize-pdf', slug:'organize-pdf', name:'Organise PDF', desc:'Drag and drop pages to reorder them visually.', category:'organize', badge:null, icon:'files', color:'rgba(127,119,221,0.2)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'delete-pages', slug:'delete-pages', name:'Delete Pages', desc:'Remove unwanted pages from your PDF document.', category:'organize', badge:null, icon:'trash-2', color:'rgba(216,90,48,0.15)', iconColor:'#F0997B', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'rotate-pdf', slug:'rotate-pdf', name:'Rotate PDF', desc:'Rotate all or selected pages by 90°, 180° or 270°.', category:'organize', badge:null, icon:'rotate-cw', color:'rgba(93,202,165,0.2)', iconColor:'#5DCAA5', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'reverse-pages', slug:'reverse-pages', name:'Reverse Pages', desc:'Flip the entire page order of your PDF.', category:'organize', badge:null, icon:'arrow-left-right', color:'rgba(239,159,39,0.15)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'add-blank-page', slug:'add-blank-page', name:'Add Blank Page', desc:'Insert blank pages at any position in your PDF.', category:'organize', badge:null, icon:'file-plus', color:'rgba(55,138,221,0.15)', iconColor:'#85B7EB', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'n-up-pdf', slug:'n-up-pdf', name:'N-Up PDF', desc:'Print multiple pages on a single sheet (2-up, 4-up, 6-up).', category:'organize', badge:null, icon:'layout-grid', color:'rgba(127,119,221,0.15)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'alternate-merge', slug:'alternate-merge', name:'Alternate Merge', desc:'Interleave pages from two PDFs — perfect for double-sided scans.', category:'organize', badge:null, icon:'git-merge', color:'rgba(93,202,165,0.15)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'divide-pages', slug:'divide-pages', name:'Divide Pages', desc:'Split each page horizontally or vertically into two pages.', category:'organize', badge:null, icon:'separator-horizontal', color:'rgba(216,90,48,0.12)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'combine-single', slug:'combine-single', name:'Combine Single', desc:'Stitch all pages continuously into one tall scrollable page.', category:'organize', badge:null, icon:'align-center-vertical', color:'rgba(55,138,221,0.12)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'pdf-booklet', slug:'pdf-booklet', name:'PDF Booklet', desc:'Rearrange pages for double-sided folded booklet printing.', category:'organize', badge:null, icon:'book-open', color:'rgba(239,159,39,0.12)', iconColor:'#EF9F27', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'pdf-reader', slug:'pdf-reader', name:'PDF Reader', desc:'View any PDF directly in your browser with a clean reader interface.', category:'organize', badge:'free', icon:'book', color:'rgba(93,202,165,0.1)', iconColor:'#5DCAA5', working:true, accepts:['.pdf'], output:null },
  { id:'view-metadata', slug:'view-metadata', name:'View Metadata', desc:'Inspect author, title, creation date and all PDF properties.', category:'organize', badge:null, icon:'info', color:'rgba(127,119,221,0.12)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:null },
  { id:'edit-metadata', slug:'edit-metadata', name:'Edit Metadata', desc:'Update author, title, subject, keywords and creation date.', category:'organize', badge:null, icon:'pencil', color:'rgba(55,138,221,0.1)', iconColor:'#85B7EB', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'compare-pdfs', slug:'compare-pdfs', name:'Compare PDFs', desc:'Visually highlight differences between two PDF versions.', category:'organize', badge:'pro', icon:'git-compare', color:'rgba(216,90,48,0.1)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:null },
  { id:'pdf-to-zip', slug:'pdf-to-zip', name:'PDF to ZIP', desc:'Package multiple PDFs into a single ZIP archive for sharing.', category:'organize', badge:null, icon:'archive', color:'rgba(239,159,39,0.1)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'zip' },
  { id:'posterize-pdf', slug:'posterize-pdf', name:'Posterize PDF', desc:'Tile large pages across multiple A4/Letter sheets for printing.', category:'organize', badge:null, icon:'table', color:'rgba(93,202,165,0.08)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'grid-combine', slug:'grid-combine', name:'Grid Combine', desc:'Merge multiple PDFs into a structured grid layout.', category:'organize', badge:null, icon:'grid', color:'rgba(127,119,221,0.08)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'ocr-pdf', slug:'ocr-pdf', name:'OCR PDF', desc:'Add an invisible searchable text layer to scanned PDFs.', category:'organize', badge:null, icon:'scan-text', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'extract-images', slug:'extract-images', name:'Extract Images', desc:'Pull all embedded images from a PDF as individual files.', category:'organize', badge:null, icon:'image', color:'rgba(216,90,48,0.12)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:'zip' },
  { id:'add-attachments', slug:'add-attachments', name:'Add Attachments', desc:'Embed any file type into a PDF as an attachment.', category:'organize', badge:null, icon:'paperclip', color:'rgba(239,159,39,0.12)', iconColor:'#EF9F27', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'extract-attachments', slug:'extract-attachments', name:'Extract Attachments', desc:'Download all files embedded as attachments in a PDF.', category:'organize', badge:null, icon:'download', color:'rgba(93,202,165,0.1)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'zip' },
  // ── EDIT & ANNOTATE ────────────────────────────────────────────────────────
  { id:'edit-pdf', slug:'edit-pdf', name:'Edit PDF', desc:'Annotate, highlight, draw shapes, add text and images directly.', category:'edit', badge:'pro', icon:'pocket-knife', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'sign-pdf', slug:'sign-pdf', name:'Sign PDF', desc:'Draw, type or upload a signature and place it anywhere.', category:'edit', badge:null, icon:'pen-tool', color:'rgba(127,119,221,0.2)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'crop-pdf', slug:'crop-pdf', name:'Crop PDF', desc:'Trim page margins and adjust bounding boxes precisely.', category:'edit', badge:null, icon:'crop', color:'rgba(93,202,165,0.15)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'add-watermark', slug:'add-watermark', name:'Add Watermark', desc:'Stamp text or image watermarks on every page.', category:'edit', badge:null, icon:'droplets', color:'rgba(239,159,39,0.15)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'page-numbers', slug:'page-numbers', name:'Page Numbers', desc:'Add customisable page numbers to headers or footers.', category:'edit', badge:null, icon:'hash', color:'rgba(216,90,48,0.15)', iconColor:'#F0997B', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'header-footer', slug:'header-footer', name:'Header & Footer', desc:'Add consistent header and footer text on every page.', category:'edit', badge:null, icon:'layout-template', color:'rgba(55,138,221,0.12)', iconColor:'#85B7EB', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'edit-bookmarks', slug:'edit-bookmarks', name:'Edit Bookmarks', desc:'Add, remove and restructure PDF bookmark outlines.', category:'edit', badge:null, icon:'bookmark', color:'rgba(93,202,165,0.12)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'table-of-contents', slug:'table-of-contents', name:'Table of Contents', desc:'Auto-generate a clickable TOC from existing bookmarks.', category:'edit', badge:null, icon:'list', color:'rgba(127,119,221,0.12)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'invert-colors', slug:'invert-colors', name:'Invert Colors', desc:'Create a dark-mode version by inverting all page colours.', category:'edit', badge:null, icon:'sun-moon', color:'rgba(239,159,39,0.1)', iconColor:'#EF9F27', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'background-color', slug:'background-color', name:'Background Colour', desc:'Change the background colour of all PDF pages.', category:'edit', badge:null, icon:'palette', color:'rgba(216,90,48,0.1)', iconColor:'#F0997B', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'add-stamps', slug:'add-stamps', name:'Add Stamps', desc:'Apply predefined stamps like APPROVED, DRAFT, CONFIDENTIAL.', category:'edit', badge:null, icon:'stamp', color:'rgba(55,138,221,0.1)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'form-filler', slug:'form-filler', name:'Form Filler', desc:'Fill out interactive PDF forms including XFA forms.', category:'edit', badge:null, icon:'form-input', color:'rgba(93,202,165,0.1)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'form-creator', slug:'form-creator', name:'Form Creator', desc:'Add text boxes, checkboxes and dropdowns to any PDF.', category:'edit', badge:'pro', icon:'layout-list', color:'rgba(127,119,221,0.1)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'remove-annotations', slug:'remove-annotations', name:'Remove Annotations', desc:'Delete all comments, highlights and markup from a PDF.', category:'edit', badge:null, icon:'eraser', color:'rgba(239,159,39,0.08)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'remove-blank-pages', slug:'remove-blank-pages', name:'Remove Blank Pages', desc:'Auto-detect and delete empty pages from your document.', category:'edit', badge:null, icon:'file-x', color:'rgba(216,90,48,0.08)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'deskew-pdf', slug:'deskew-pdf', name:'Deskew PDF', desc:'Straighten skewed scanned pages using OpenCV correction.', category:'edit', badge:null, icon:'scan', color:'rgba(55,138,221,0.08)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  // ── OPTIMISE & REPAIR ──────────────────────────────────────────────────────
  { id:'compress-pdf', slug:'compress-pdf', name:'Compress PDF', desc:'Reduce file size without visible quality loss.', category:'optimize', badge:null, icon:'zap', color:'rgba(99,153,34,0.2)', iconColor:'#97C459', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'linearize-pdf', slug:'linearize-pdf', name:'Linearize PDF', desc:'Optimise for fast web viewing with progressive loading.', category:'optimize', badge:null, icon:'activity', color:'rgba(55,138,221,0.15)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'repair-pdf', slug:'repair-pdf', name:'Repair PDF', desc:'Attempt to fix corrupted or damaged PDF files.', category:'optimize', badge:null, icon:'wrench', color:'rgba(180,178,169,0.2)', iconColor:'#B4B2A9', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'fix-page-size', slug:'fix-page-size', name:'Fix Page Size', desc:'Standardise all pages to A4, Letter or any custom size.', category:'optimize', badge:null, icon:'ruler', color:'rgba(239,159,39,0.15)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'page-dimensions', slug:'page-dimensions', name:'Page Dimensions', desc:'View and analyse dimensions and orientation of every page.', category:'optimize', badge:null, icon:'maximize', color:'rgba(93,202,165,0.12)', iconColor:'#5DCAA5', working:true, accepts:['.pdf'], output:null },
  { id:'remove-restrictions', slug:'remove-restrictions', name:'Remove Restrictions', desc:'Strip edit/print locks from permission-protected PDFs.', category:'optimize', badge:null, icon:'lock-open', color:'rgba(216,90,48,0.12)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'rasterize-pdf', slug:'rasterize-pdf', name:'Rasterize PDF', desc:'Flatten all vectors to JPEG to prevent copy/paste.', category:'optimize', badge:null, icon:'layers', color:'rgba(127,119,221,0.12)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'font-to-outline', slug:'font-to-outline', name:'Font to Outline', desc:'Convert all text fonts to vector outlines for device independence.', category:'optimize', badge:null, icon:'type', color:'rgba(55,138,221,0.1)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  // ── SECURE ─────────────────────────────────────────────────────────────────
  { id:'protect-pdf', slug:'protect-pdf', name:'Protect PDF', desc:'Set an open password and restrict printing/copying permissions.', category:'secure', badge:null, icon:'lock', color:'rgba(239,159,39,0.2)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'unlock-pdf', slug:'unlock-pdf', name:'Unlock PDF', desc:'Remove password protection from a PDF you own.', category:'secure', badge:null, icon:'lock-open', color:'rgba(99,153,34,0.2)', iconColor:'#97C459', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'redact-pdf', slug:'redact-pdf', name:'Redact Content', desc:'Permanently black out sensitive text and images.', category:'secure', badge:null, icon:'eye-off', color:'rgba(226,75,74,0.2)', iconColor:'#F09595', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'sign-certificate', slug:'sign-certificate', name:'Digital Signature', desc:'Apply cryptographic PKI signatures using X.509 certificates.', category:'secure', badge:'pro', icon:'shield-check', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'sanitize-pdf', slug:'sanitize-pdf', name:'Sanitize PDF', desc:'Remove hidden metadata, scripts and embedded objects.', category:'secure', badge:null, icon:'shield', color:'rgba(93,202,165,0.15)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'flatten-pdf', slug:'flatten-pdf', name:'Flatten PDF', desc:'Merge form fields and annotations into static page content.', category:'secure', badge:null, icon:'layers', color:'rgba(127,119,221,0.15)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'remove-metadata', slug:'remove-metadata', name:'Remove Metadata', desc:'Strip author names, dates and custom properties.', category:'secure', badge:null, icon:'file-minus', color:'rgba(239,159,39,0.12)', iconColor:'#EF9F27', working:true, accepts:['.pdf'], output:'pdf' },
  { id:'convert-pdfa', slug:'convert-pdfa', name:'Convert to PDF/A', desc:'Create archival-compliant PDFs meeting ISO PDF/A standards.', category:'secure', badge:null, icon:'archive', color:'rgba(93,202,165,0.1)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'pdf' },
  // ── CONVERT TO PDF ─────────────────────────────────────────────────────────
  { id:'word-to-pdf', slug:'word-to-pdf', name:'Word to PDF', desc:'DOC, DOCX, ODT with full formatting and font preservation.', category:'convert-to', badge:null, icon:'file-text', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:false, accepts:['.doc','.docx','.odt','.rtf'], output:'pdf' },
  { id:'excel-to-pdf', slug:'excel-to-pdf', name:'Excel to PDF', desc:'XLS, XLSX, CSV spreadsheets with charts and all sheets.', category:'convert-to', badge:null, icon:'sheet', color:'rgba(99,153,34,0.2)', iconColor:'#97C459', working:false, accepts:['.xls','.xlsx','.csv','.ods'], output:'pdf' },
  { id:'pptx-to-pdf', slug:'pptx-to-pdf', name:'PowerPoint to PDF', desc:'PPT, PPTX slides converted to presentation-ready PDF.', category:'convert-to', badge:null, icon:'presentation', color:'rgba(216,90,48,0.2)', iconColor:'#F0997B', working:false, accepts:['.ppt','.pptx','.odp'], output:'pdf' },
  { id:'image-to-pdf', slug:'image-to-pdf', name:'Image to PDF', desc:'JPG, PNG, WEBP, HEIC — one or many images into one PDF.', category:'convert-to', badge:null, icon:'image', color:'rgba(127,119,221,0.2)', iconColor:'#AFA9EC', working:true, accepts:['.jpg','.jpeg','.png','.webp','.gif','.bmp','.tiff'], output:'pdf' },
  { id:'html-to-pdf', slug:'html-to-pdf', name:'HTML / URL to PDF', desc:'Paste a URL or upload HTML/CSS to get a pixel-perfect PDF.', category:'convert-to', badge:null, icon:'globe', color:'rgba(93,202,165,0.2)', iconColor:'#5DCAA5', working:false, accepts:['.html','.htm'], output:'pdf' },
  { id:'markdown-to-pdf', slug:'markdown-to-pdf', name:'Markdown to PDF', desc:'Convert .md files to styled, readable PDF documents.', category:'convert-to', badge:null, icon:'code', color:'rgba(55,138,221,0.15)', iconColor:'#85B7EB', working:false, accepts:['.md','.markdown'], output:'pdf' },
  { id:'epub-to-pdf', slug:'epub-to-pdf', name:'EPUB to PDF', desc:'Convert ebooks from EPUB format to PDF.', category:'convert-to', badge:null, icon:'book', color:'rgba(239,159,39,0.15)', iconColor:'#EF9F27', working:false, accepts:['.epub'], output:'pdf' },
  { id:'email-to-pdf', slug:'email-to-pdf', name:'Email to PDF', desc:'Render EML and MSG email messages as clean PDF files.', category:'convert-to', badge:null, icon:'mail', color:'rgba(93,202,165,0.12)', iconColor:'#5DCAA5', working:false, accepts:['.eml','.msg'], output:'pdf' },
  { id:'txt-to-pdf', slug:'txt-to-pdf', name:'Text to PDF', desc:'Convert plain text files to formatted, styled PDFs.', category:'convert-to', badge:null, icon:'align-left', color:'rgba(180,178,169,0.15)', iconColor:'#B4B2A9', working:false, accepts:['.txt'], output:'pdf' },
  { id:'cad-to-pdf', slug:'cad-to-pdf', name:'CAD to PDF', desc:'Plot DWG and DXF AutoCAD drawings to vector-accurate PDFs.', category:'convert-to', badge:'pro', icon:'drafting-compass', color:'rgba(180,178,169,0.1)', iconColor:'#888780', working:false, accepts:['.dwg','.dxf'], output:'pdf' },
  { id:'psd-to-pdf', slug:'psd-to-pdf', name:'PSD / AI to PDF', desc:'Flatten Photoshop and Illustrator files into shareable PDFs.', category:'convert-to', badge:'pro', icon:'layers', color:'rgba(212,83,126,0.15)', iconColor:'#ED93B1', working:false, accepts:['.psd','.ai','.eps'], output:'pdf' },
  // ── CONVERT FROM PDF ───────────────────────────────────────────────────────
  { id:'pdf-to-word', slug:'pdf-to-word', name:'PDF to Word', desc:'Extract editable DOCX from any PDF — best-effort layout recovery.', category:'convert-from', badge:null, icon:'file-text', color:'rgba(55,138,221,0.2)', iconColor:'#85B7EB', working:false, accepts:['.pdf'], output:'docx' },
  { id:'pdf-to-excel', slug:'pdf-to-excel', name:'PDF to Excel', desc:'Extract tables from PDF into XLSX spreadsheets ready for editing.', category:'convert-from', badge:null, icon:'table', color:'rgba(99,153,34,0.2)', iconColor:'#97C459', working:false, accepts:['.pdf'], output:'xlsx' },
  { id:'pdf-to-pptx', slug:'pdf-to-pptx', name:'PDF to PowerPoint', desc:'Convert PDF pages into editable PPTX presentation slides.', category:'convert-from', badge:null, icon:'presentation', color:'rgba(216,90,48,0.15)', iconColor:'#F0997B', working:false, accepts:['.pdf'], output:'pptx' },
  { id:'pdf-to-jpg', slug:'pdf-to-jpg', name:'PDF to JPG', desc:'Render each PDF page as a high-resolution JPEG image.', category:'convert-from', badge:null, icon:'image', color:'rgba(127,119,221,0.2)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:'jpg' },
  { id:'pdf-to-png', slug:'pdf-to-png', name:'PDF to PNG', desc:'Convert PDF pages to high-resolution PNG images.', category:'convert-from', badge:null, icon:'image', color:'rgba(127,119,221,0.15)', iconColor:'#AFA9EC', working:true, accepts:['.pdf'], output:'png' },
  { id:'pdf-to-text', slug:'pdf-to-text', name:'PDF to Text', desc:'Extract all text from a PDF as plain TXT or structured JSON.', category:'convert-from', badge:null, icon:'file-text', color:'rgba(180,178,169,0.15)', iconColor:'#B4B2A9', working:true, accepts:['.pdf'], output:'txt' },
  { id:'pdf-to-epub', slug:'pdf-to-epub', name:'PDF to EPUB', desc:'Convert PDF content into a reflowable EPUB ebook.', category:'convert-from', badge:null, icon:'book', color:'rgba(239,159,39,0.15)', iconColor:'#EF9F27', working:false, accepts:['.pdf'], output:'epub' },
  { id:'pdf-to-html', slug:'pdf-to-html', name:'PDF to HTML', desc:'Convert PDF pages into HTML for web embedding or editing.', category:'convert-from', badge:'new', icon:'globe', color:'rgba(93,202,165,0.15)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:'html' },
  { id:'pdf-to-csv', slug:'pdf-to-csv', name:'PDF to CSV', desc:'Extract tabular data from PDF into CSV format.', category:'convert-from', badge:null, icon:'database', color:'rgba(99,153,34,0.15)', iconColor:'#97C459', working:false, accepts:['.pdf'], output:'csv' },
  // ── AI ─────────────────────────────────────────────────────────────────────
  { id:'summarize-pdf', slug:'summarize-pdf', name:'Summarise PDF', desc:'Get a clear, structured AI summary of any PDF document.', category:'ai', badge:'ai', icon:'sparkles', color:'rgba(93,202,165,0.2)', iconColor:'#5DCAA5', working:false, accepts:['.pdf'], output:null },
  { id:'translate-pdf', slug:'translate-pdf', name:'Translate PDF', desc:'Translate a PDF into 50+ languages, layout fully preserved.', category:'ai', badge:'ai', icon:'languages', color:'rgba(239,159,39,0.2)', iconColor:'#EF9F27', working:false, accepts:['.pdf'], output:'pdf' },
  { id:'chat-pdf', slug:'chat-pdf', name:'Chat with PDF', desc:'Ask questions about your document and get AI answers with citations.', category:'ai', badge:'ai', icon:'message-circle', color:'rgba(127,119,221,0.2)', iconColor:'#AFA9EC', working:false, accepts:['.pdf'], output:null },
];

export function getToolBySlug(slug) {
  return ALL_TOOLS.find(t => t.slug === slug) || null;
}

export function getToolsByCategory(category) {
  return ALL_TOOLS.filter(t => t.category === category);
}

export function searchTools(query) {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_TOOLS;
  return ALL_TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.desc.toLowerCase().includes(q) ||
    (t.accepts || []).some(a => a.includes(q))
  );
}
